#!/bin/bash
mount -t proc proc proc
mount -t sysfs sys sys
mount -t debugfs debug sys/kernel/debug
modprobe virtio
modprobe virtio_pci
modprobe virtio_net
modprobe virtio_blk
dhclient -v eth0 &
mknod /dev/vda b 254 0
mknod /dev/vdb b 254 8
zsh < /dev/vda > /dev/vdb
sync
poweroff -f
